#example.property: "I AM A PROD PROPERTY OVERRIDE"
#spring.jpa.database: "POSTGRESQL"
#spring.datasource.platform:  "postgres"
#spring.jpa.show-sql: "true"
#spring.database.driverClassName: "org.postgresql.Driver"
#spring.datasource.url: "jdbc:postgresql://192.168.99.100:5432/eagle_eye_prod"
#spring.datasource.username: "postgres_prod"
#spring.datasource.password: "p0stgr@s_prod"
#spring.datasource.testWhileIdle: "true"
#spring.datasource.validationQuery: "SELECT 1"
#spring.jpa.properties.hibernate.dialect: "org.hibernate.dialect.PostgreSQLDialect"

example.property: "I AM IN THE DEFAULT"
spring.jpa.database: "POSTGRESQL"
spring.datasource.platform:  "postgres"
spring.datasource.initialization-mode: always
spring.jpa.show-sql: "true"
spring.database.driverClassName: "org.postgresql.Driver"
spring.datasource.url: "jdbc:postgresql://localhost:5432/product"
spring.datasource.username: "dbexerphi_dba"
spring.datasource.password: "admin"
spring.datasource.testWhileIdle: "true"
spring.datasource.validationQuery: "SELECT 1"
spring.jpa.properties.hibernate.dialect: "org.hibernate.dialect.PostgreSQLDialect"
spring.cloud.refresh.enabled: false
redis.server: "redis"
redis.port: "6379"
